### PR TITLE
Remove obsolete/broken indexer tests

### PR DESCRIPTION
**Pull request by HannesWell**
Since the last change (commit 1b22962461b08b45180b1a948c4735981c08cfe6) there the implicitly required class `org.apache.maven.index.ArtifactInfo` is missing in `NexusIndexManagerSearchTest` and `NexusIndexManagerTest`.
This is indicated by an error marker in the IDE and leads to test failures like (see build output of PR https://github.com/eclipse-m2e/m2e-core/pull/511):
```
java.lang.NoClassDefFoundError: org/apache/maven/index/ArtifactInfo
	at org.eclipse.m2e.tests.internal.index.NexusIndexManagerTest.testIndexedArtifactGroups(NexusIndexManagerTest.java:296)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.index.ArtifactInfo cannot be found by org.eclipse.m2e.tests_1.17.2.qualifier
	at org.eclipse.m2e.tests.internal.index.NexusIndexManagerTest.testIndexedArtifactGroups(NexusIndexManagerTest.java:296)
```
I'm not sure why only org.eclipse.m2e.tests.internal.index.NexusIndexManagerTest.testIndexedArtifactGroups() failed in the mentioned build, but in Eclipse the error massage `The type org.apache.maven.index.ArtifactInfo cannot be resolved. It is indirectly referenced from required .class files ` only vanishes after both classes are deleted.

Furthermore if I understand the tests right, the entire test class `NexusIndexManagerSearchTest` and `NexusIndexManagerTest` are obsolete once the required-bundle `org.eclipse.m2e.maven.indexer` is gone respectivly the corresponding Indexer classes in m2e.
@mickaelistria please correct me if I'm wrong.

### CODE REVIEW

**Comment by HannesWell** [comment]
Additionally I deleted associated and now unused resources.

**Comment by mickaelistria** [comment]
indexer is not yet gone, it's still work in progress.
I don't mind deleting tests, but before that, I'd rather wait for verification that m2e can work without using indexer. It may be that indexer is used somewhere deeper.

**Comment by HannesWell** [comment]
> indexer is not yet gone, it's still work in progress. I don't mind deleting tests, but before that, I'd rather wait for verification that m2e can work without using indexer. It may be that indexer is used somewhere deeper.

Yes, I agree and my intention was not to delete the indexer tests prematurely, but to make the PR builds of m2e-core work again. At the moment they are all failing with the same error (I'm not sure why the master build succeeded).
Additionally I have the following error in my m2e Eclipse workspace:
grafik

When I delete the failing test method that error pops up at the next method and when I delete NexusIndexManagerSearchTest it show at NexusIndexManagerTest. Therefore I assumed that both test classes are now obsolete since you removed all indexer references.

Alternatively the compiler error is fixed in the IDE when I add the Require-bundle `org.eclipse.m2e.maven.indexer` back to the manifest of `org.eclipse.m2e.tests`. I just started a local m2e-core build to check if this also lets the build pass. If yes I suggest to re-add that require build to have green check-marks in m2e builds again :)

**Comment by HannesWell** [comment]
> If yes I suggest to re-add that require build to have green check-marks in m2e builds again :)

It can then be removed again as soon as the indexer is really gone in m2e-core.

**Comment by mickaelistria** [comment]
Are those tests currently executed? If they are, I suggest we keep them until we actually start removing all indexer stuff from m2e-core.

**Comment by HannesWell** [comment]
> Are those tests currently executed? If they are, I suggest we keep them until we actually start removing all indexer stuff from m2e-core.

Yes they are executed at the moment. Fully agree!

**Pull request merged**
