### PR TITLE
NPE in MavenSession.getAllProjects()

### PR DESCRIPTION
**Pull request by snjeza**
Test for https://github.com/eclipse-m2e/m2e-core/pull/1221

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Comment by laeubi** [comment]
@snjeza please contribute new tests directly to m2eclipse repository if possible.

**Comment by snjeza** [comment]
> please contribute new tests directly to m2eclipse repository if possible.

Could you, please, explain me how to do it?

**Comment by laeubi** [comment]
You can add your test for example here:
https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.core.tests

**Comment by snjeza** [comment]
I have moved it to https://github.com/eclipse-m2e/m2e-core/pull/1221/commits/9ea187c723476e80e9a9b7c440ab390f1b0e607c#diff-1b6a4c66cbe53cef1a22cbd6aebfbde808e4fc3c585723adb2e36106ff557acaR119

**Pull request closed without merging**
