### PR TITLE
Replace deprecated methods, fix warnings and use Mockito.

### PR DESCRIPTION
**Pull request by HannesWell**
A first bunch of changes to replace deprecated API in the tests and to perform general clean-up.

It has not yet been tested and a verification-build should succeed in m2e-core first.

### CODE REVIEW

**Comment by HannesWell** [comment]
As soon as https://github.com/eclipse-m2e/m2e-core/pull/674 has succeeded this can be submitted.

**Comment by mickaelistria** [comment]
1 issue to lookup: https://ci.eclipse.org/m2e/job/m2e/job/PR-674/2/testReport/org.eclipse.m2e.tests.project/MavenProjectFacadeTest/testIsStale/

**Comment by mickaelistria** [comment]
Thanks a lot for that!

**Comment by mickaelistria** [comment]
I'll try but I'm not sure I have enough power against this repo to do so. We'll see.

**Comment by laeubi** [comment]
I know there where some concerns regarding licensing, but a we do not *deliver* any code from this might it be an option to just *fork* this to the m2e organization?

**Comment by laeubi** [comment]
> I tried and failed, several times. Eclipse doesn't really care about what's delivered;

@waynebeaton any chance we can make progress here? I have read some things where relaxed recently so maybe we can have something more useful here than two repos in different organizations?

**Pull request merged**
